### ISSUE TITLE
What are the formats for the various destination files?

### ISSUE THREAD

**Issue by mshoward** [FourthCohortAwesome/NightThree#1]
If I recall correctly, dest_alt1 is a tab separated value file, but is dest_alt2 tab separated?  or do we leave the <val>:<other_val>\n format as it is?

Also, I'd like to verify that dest_alt3 is supposed to be tab separated, too.

**Comment by diazgilberto** [comment]
All the output files are \t.

**Comment by xianarchangel** [comment]
I thought the files were supposed to maintain what was passed in

**Comment by philipdbest** [comment]
All three files should be standardized to tab separated files.


On Mar 1, 2017, 10:09 AM -0600, David Keough <notifications@github.com>, wrote:
I thought the files were supposed to maintain what was passed in

**Comment by mshoward** [comment]
Thank you!
